### PR TITLE
add method(s) for setting a proxy

### PR DESCRIPTION
**Pull request by vlovo**
under some ciurcumstances we operate  behind a proxy server  and therefore the ability to set  the proxy url  to curl might be handy

### CODE REVIEW

**Comment by coin-au-carre** [comment]
Thank you @vlovo for this improvement!

**Comment by vlovo** [comment]
Thank you @coin-au-carre  for  writing this nice piece of sw ! 
I originally wanted to post to a slack web hook...Took me a while to figure out that slack web api is the game here.  Anyway it runs for me under  VS 2017 @Windows7 like a charme. 
I made small additions to CMakeLists.txt  too, but I did not get the appveyor thing so far. Why is it opt in a special manner ?

**Comment by coin-au-carre** [comment]
Hello @vlovo never tried on Windows. I am really glad and surprised that it works without some tweaks !
 
The appveyor configuration is available here: https://ci.appveyor.com/project/coin-au-carre/slacking . I am not sure how to make it work properly so I deactivated it for the moment. Feel free to add PR.
 
And btw I don't know why you are not yet visible in the contributors list

**Comment by vlovo** [comment]
Hello Florian, 

thing is that:    

target_link_libraries(${name} ${CURL_LIBRARIES}) 

works the same on windows due to  find_package(CURL).

That said the appveyor configuration is odd and needs maybe an optional settings concerning the library name ?

**Pull request merged**
